ibm:
  mq:
    queueManager: QM1
    channel: CLOUD.APP.SVRCONN
    connName: qm1-0bbd.qm.us-south.mq.appdomain.cloud(32625)
    user: kafkaconnect
    password: <password>
#jms:
#  mq:
#    inbound-default-queue: